### ISSUE TITLE
dotnetcore

### ISSUE THREAD

**Issue by Dirtypaws** [efaruk/yakari#2]
I think a library like this would be extremely helpful on dotnetcore, I have a host of dotnetcore applications running in docker containers and the caching mechanisms would really shine with a shared redis container.

I forked and migrated a lot of the code to dotnetcore already. Most of the changes were in the unit test and demo project. There were some timer changes - and I'll be honest, I didn't really look into the code too closely to see how the timers were being used. Just migrated them to the System.Threading.Timers namespace, as the System.Timer isn't available in dotnetcore. But, all the tests pass - so long as the tests were covering their usage, should be good to go.
https://github.com/Dirtypaws/yakari/commit/d7d3f79ba1de15e520c60930d0fd61c963c6fb1b

Not sure if you want to put this on a separate repository or just a dotnetcore branch. I can set up a PR if you'd like. If not, I wouldn't mind setting this up as a new repo and maintaining it myself.

**Comment by efaruk** [comment]
Would you like to join us and implement/maintain dotnet core compatibility ?

**Comment by Dirtypaws** [comment]
I think youre right, we'll use the same repo. I'll set up a new solution with projects using a .core suffix. So it would be Yakari.Core and Yakari.Core.Redis etc...

**Comment by efaruk** [comment]
Yes absolutely and we can link original *.cs files to core projects. If you need help you can check https://github.com/NancyFx/Nancy solution/project structure.

**Comment by efaruk** [comment]
If you want to create Yakari and Yakari.Core root folders for solution level seperation please let me know...

**Comment by Dirtypaws** [comment]
dotnetcore projects don't support file linking like that yet. I think there's a way to do it through the xproj with manual editing - so I can look into that.

**Comment by efaruk** [comment]
We may also support mono!? How about that? The code base should be compatible with both dotnetcore and mono...

**Comment by efaruk** [comment]
I think NancyFx team handling this very well: (Without linking of course as you mentioned) https://github.com/NancyFx/Nancy

If you could check Nancy.sln Nancy.Next.sln it's showing the way...

**Comment by Dirtypaws** [comment]
Ahhh - I see. They used the dotnet core xproj's to house all of the files then they created csproj's to link the csproj files to link the files from the xproj. Interesting approach - I'll see what it takes to do that.

I'm not too familiar with Mono conversions - but - I imagine if the code works for dotnetcore it'll work for mono. The biggest issue I would see there is the libraries supporting mono. But, again - if they work with core they should work with Mono.

**Comment by efaruk** [comment]
Xbuild and msbuild almost same...

**Comment by efaruk** [comment]
I want to give you AppVayor access case of if any further requirement and there is no private message feature at github, how can i learn your e-mail adress?

**Comment by Dirtypaws** [comment]
I sent it to you on Twitter - along with a request to the slack channel

**Comment by efaruk** [comment]
I think github faster then twitter, your comment mail arrived but no Twitter message ;)

**Comment by efaruk** [comment]
My twitter profile is https://twitter.com/farukpehlivanli

**Comment by Dirtypaws** [comment]
matthewkrizanac@gmail.com

**Comment by efaruk** [comment]
I have given Admin access to AppVeyor...

**Comment by efaruk** [comment]
Hi Matt, I'm having issues buildin Yakari.Core.sln on Ubuntu 16.04: (Ubuntu Mate 16.04)

Error:null: Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'ubuntu.16.04-x64'. Possible causes:
Error:null: 1. The project has not been restored or restore failed - run `dotnet restore`
Error:null: 2. The project does not list one of 'ubuntu.16.04-x64' in the 'runtimes' section.
Error:null: 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.

Note: I have tried with following project.json additions but i'm getting same output

"runtimes": {
      "linux-x64": {}
    }

Is there any guidance or reference for me ?

**Comment by Dirtypaws** [comment]
Nope, it's not that. It's just a thing that happens when a nuget package updates through the tool. It's supposed to keep the body of the package, but, it just replaces it with a version number. Check my last two commits

**Comment by efaruk** [comment]
Do we have any works to do for dotnetcore or could we close the issue?

**Comment by Dirtypaws** [comment]
I think we can close, but, i think we need to discuss a settings/config
indirection

**Comment by efaruk** [comment]
I have created new issue #9 for that...
